FROM php:8.3-apache

RUN apt-get update && apt-get upgrade -y
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable mysqli pdo pdo_mysql
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

EXPOSE 80